# Generated by Django 2.0.2 on 2018-08-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_related_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_photo',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
