# Generated by Django 2.1 on 2018-09-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_alt_text',
            field=models.CharField(default='alt_text', max_length=200),
            preserve_default=False,
        ),
    ]
