# Generated by Django 2.2.6 on 2019-10-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
