# Generated by Django 2.1 on 2019-07-03 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
